src/Entity/Demande.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use App\Repository\DemandeRepository;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: DemandeRepository::class)]
#[ORM\Table(name: 'demande')]
class Demande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'idDem', type: 'integer')]
    private ?int $idDem = null;

    public function getIdDem(): ?int
    {
        return $this->idDem;
    }

    public function setIdDem(int $idDem): self
    {
        $this->idDem = $idDem;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: false)]
    #[Assert\NotBlank(message: 'Le type est obligatoire')]
    #[Assert\Choice(
        choices: ['Attestation de Travail', 'Attestation de Salaire'],
        message: 'Veuillez sélectionner un type valide.'
    )]
    private ?string $type = null;

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: false)]
    private ?string $statut = null;

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;
        return $this;
    }

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $date_soumission = null;

    public function getDateSoumission(): ?\DateTime
    {
        return $this->date_soumission;
    }

    public function setDateSoumission(\DateTime $date_soumission): static
    {
        $this->date_soumission = $date_soumission;

        return $this;
    }

    

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'demandes')]
    #[ORM\JoinColumn(name: 'employe_id', referencedColumnName: 'id',nullable: false)]
    private ?User $user = null;

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;
        return $this;
    }

    #[ORM\OneToMany(targetEntity: HistoriqueDemande::class, mappedBy: 'demande')]
    private Collection $historiqueDemandes;

    public function __construct()
    {
        $this->historiqueDemandes = new ArrayCollection();
         $this->date_soumission = new \DateTime(); // date et heure actuelles
        $this->statut = 'en attente'; // valeur par défaut

    
    }

    /**
     * @return Collection<int, HistoriqueDemande>
     */
    public function getHistoriqueDemandes(): Collection
    {
        if (!$this->historiqueDemandes instanceof Collection) {
            $this->historiqueDemandes = new ArrayCollection();
        }
        return $this->historiqueDemandes;
    }

    public function addHistoriqueDemande(HistoriqueDemande $historiqueDemande): self
    {
        if (!$this->getHistoriqueDemandes()->contains($historiqueDemande)) {
            $this->getHistoriqueDemandes()->add($historiqueDemande);
        }
        return $this;
    }

    public function removeHistoriqueDemande(HistoriqueDemande $historiqueDemande): self
    {
        $this->getHistoriqueDemandes()->removeElement($historiqueDemande);
        return $this;
    }

    

   

}
 

src/Entity/HistoriqueDemande.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use App\Repository\HistoriqueDemandeRepository;

#[ORM\Entity(repositoryClass: HistoriqueDemandeRepository::class)]
#[ORM\Table(name: 'historique_demande')]
class HistoriqueDemande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'idHisto', type: 'integer')]
    private ?int $idHisto = null;

    public function getIdHisto(): ?int
    {
        return $this->idHisto;
    }

    public function setIdHisto(int $idHisto): self
    {
        $this->idHisto = $idHisto;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: false)]
    private ?string $action = null;

    public function getAction(): ?string
    {
        return $this->action;
    }

    public function setAction(string $action): self
    {
        $this->action = $action;
        return $this;
    }

    #[ORM\Column(type: 'datetime', nullable: false)]
    private ?\DateTimeInterface $date_action = null;

    public function getDate_action(): ?\DateTimeInterface
    {
        return $this->date_action;
    }

    public function setDate_action(\DateTimeInterface $date_action): self
    {
        $this->date_action = $date_action;
        return $this;
    }

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $commentaire = null;

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;
        return $this;
    }

    #[ORM\ManyToOne(targetEntity: Demande::class, inversedBy: 'historiqueDemandes')]
    #[ORM\JoinColumn(name: 'demande_id', referencedColumnName: 'idDem')]
    private ?Demande $demande = null;

    public function getDemande(): ?Demande
    {
        return $this->demande;
    }

    public function setDemande(?Demande $demande): self
    {
        $this->demande = $demande;
        return $this;
    }

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'historiqueDemandes')]
    #[ORM\JoinColumn(name: 'acteur_id', referencedColumnName: 'id')]
    private ?User $user = null;

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;
        return $this;
    }

    public function getDateAction(): ?\DateTime
    {
        return $this->date_action;
    }

    public function setDateAction(\DateTime $date_action): static
    {
        $this->date_action = $date_action;

        return $this;
    }

}

src/Entity/Pret.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use App\Repository\PretRepository;

#[ORM\Entity(repositoryClass: PretRepository::class)]
#[ORM\Table(name: 'pret')]
class Pret
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;
        return $this;
    }

    #[ORM\Column(type: 'decimal', nullable: false)]
    private ?float $montant = null;

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;
        return $this;
    }

    #[ORM\Column(type: 'integer', nullable: false)]
    private ?int $duree = null;

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $raison = null;

    public function getRaison(): ?string
    {
        return $this->raison;
    }

    public function setRaison(?string $raison): self
    {
        $this->raison = $raison;
        return $this;
    }

    #[ORM\Column(type: 'datetime', nullable: false)]
    private ?\DateTimeInterface $date_demande = null;

    public function getDate_demande(): ?\DateTimeInterface
    {
        return $this->date_demande;
    }

    public function setDate_demande(\DateTimeInterface $date_demande): self
    {
        $this->date_demande = $date_demande;
        return $this;
    }

    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $statut = null;

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): self
    {
        $this->statut = $statut;
        return $this;
    }

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'prets')]
    #[ORM\JoinColumn(name: 'employe_id', referencedColumnName: 'id')]
    private ?User $user = null;

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;
        return $this;
    }

    public function getDateDemande(): ?\DateTime
    {
        return $this->date_demande;
    }

    public function setDateDemande(\DateTime $date_demande): static
    {
        $this->date_demande = $date_demande;

        return $this;
    }

}

src/Form/DemandeType.php
<?php

namespace App\Form;

use App\Entity\Demande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DemandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type', ChoiceType::class, [
                'label' => 'Type de demande',
                'choices' => [
                    'Attestation de Travail' => 'Attestation de Travail',
                    'Attestation de Salaire' => 'Attestation de Salaire',
                    
                ],
                'placeholder' => 'Sélectionnez  ',
                'attr' => ['class' => 'form-control']
            ])
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Demande::class,
        ]);
    }
}

templates/demande/_delete_form.html.twig
<form method="post" action="{{ path('app_demande_delete', {'idDem': demande.idDem}) }}"
      onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette demande ?');"
      style="display:inline;">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ demande.idDem) }}">
    <button type="submit" class="btn btn-sm btn-danger">
        <i class="fas fa-trash-alt"></i> Supprimer
    </button>
</form>

templates/demande/_form.html.twig
<!-- Basic form layout section start -->
<section id="basic-form-layouts">
    <div class="row match-height justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Formulaire de demande</h4>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body">
                        {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}


                        <div class="form-body">
                            <h4 class="form-section"><i class="ft-user"></i> Demande d'attestaion</h4>

                            <div class="form-group">
                                {{ form_label(form.type) }}
                                {{ form_widget(form.type, {'attr': {'class': 'form-control'}}) }}
                                {% if form_errors(form.type) %}
                                    <div class="alert alert-danger mt-2 p-2 rounded">
                                        {{ form_errors(form.type) }}
                                    </div>
                                {% endif %}
                            </div>

                           


                        </div>

                        <div class="form-actions mt-3">
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-check-square-o"></i> {{ button_label|default('Enregistrer') }}
                            </button>
                            <a href="{{ path('app_demande_index') }}" class="btn btn-secondary ml-2">Annuler</a>
                        </div>

                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- // Basic form layout section end -->

templates/demande/edit.html.twig
{% extends 'baseF.html.twig' %}

{% block title %}Edit Demande{% endblock %}

{% block body %}
    <h1>Edit Demande</h1>

    {{ include('demande/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_mes_demandes') }}" class="btn btn-outline-secondary btn-sm">
       <i class="fas fa-arrow-left"></i> Retour 
    </a>


    {{ include('demande/_delete_form.html.twig') }}
{% endblock %}

templates/demande/historiqueDemande.html.twig
{% extends 'baseF.html.twig' %}
{% block body %}
<h4>Historique des demandes</h4>
<table class="table table-bordered">
    <thead class="table-success">
        <tr>
            <th>Type de la demande</th>
            <th>Action</th>
            <th>Date</th>
            <th>Effectué par</th>
            <th>Commentaire</th>
        </tr>
    </thead>
    <tbody>
        {% for historique in historiques %}
    <tr>
        <td>{{ historique.demande.type }}</td>
        <td>{{ historique.action }}</td>
        <td>{{ historique.dateAction ? historique.dateAction|date('d/m/Y H:i') : '' }}</td>
        <td>{{ historique.user ? historique.user.nom : 'N/A' }}</td>
        <td>{{ historique.commentaire }}</td>
    </tr>
        {% else %}
            <tr><td colspan="4">Aucun historique.</td></tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/demande/index.html.twig
{% extends 'baseF.html.twig' %}

{% block body %}
    <h1 class="mb-4">Tout les attestaions</h1>

    {% if demandes is empty %}
        <div class="alert alert-info mt-3">Aucun attestation trouvé.</div>
    {% else %}
        <table class="table table-striped table-bordered">
            <thead class="bg-primary text-white">                <tr>
                   <th>Employé</th>
                    <th>Type de la demande</th>
                    <th>Statut</th>
                    <th>Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for demande in demandes %}
                    <tr>
                         <td>{{ demande.user.nom }}</td>
                        <td>{{ demande.type }}</td>
                        <td>
                            
                            {% if demande.statut == 'Validée' %}
                                <span class="badge bg-success">{{ demande.statut }}</span>
                            {% elseif demande.statut == 'En attente' %}
                                <span class="badge bg-warning text-dark">{{ demande.statut }}</span>
                            {% elseif demande.statut == 'Rejetée' %}
                                <span class="badge bg-danger">{{ demande.statut }}</span>
                            {% else %}
                                <span class="badge bg-secondary">{{ demande.statut }}</span>
                            {% endif %}
                        
                        </td>
                        
                        <td>{{ demande.dateSoumission|date('d/m/Y') }}</td>
                        <td>
                            {% if demande.statut == 'En attente' %}
                                <a href="{{ path('admin_demande_valider', {'idDem': demande.idDem}) }}" class="btn btn-success btn-sm">Valider</a>
                                <a href="{{ path('admin_demande_rejeter', {'idDem': demande.idDem}) }}" class="btn btn-danger btn-sm">Rejeter</a>
                            
                            {% endif %}
                          
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="navigation">
            {{ knp_pagination_render(demandes) }}
        </div>

    {% endif %}  
    

       
{% endblock %}

templates/demande/listePret.html.twig
{% extends 'baseF.html.twig' %}

{% block body %}
    
    

        <div class="row">
            <h1 class="mb-4">Tout les prets</h1>
                    <div class="col-lg-12 col-md-12 col-12">
                        <div class="card">
                            
                            <div class="card-content">
                                <div class="card-body">
                                    
                                     {% if prets is empty %}
                                      <div class="alert alert-info mt-3">Aucun prêt trouvé.</div>
                                    {% else %}
                                        <table class="table table-striped table-bordered">
                                            <thead class="bg-primary text-white">              
                                                <tr>
                                                    <th>Employé</th>
                                                    <th>Montant</th>
                                                    <th>Raison</th>
                                                    <th>Date</th>
                                                    <th>Statut</th>
                                                    <th>Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                    {% for pret in prets %}
                                        <tr>
                                            <td>{{ pret.user.nom }}</td>
                                            <td>{{ pret.montant }}</td>
                                            <td>{{ pret.raison }}</td>
                                            <td>{{ pret.dateDemande|date('d/m/Y') }}</td>
                                            <td>
                                                {% if pret.statut == 'Validé' %}
                                                    <span class="badge bg-success">{{ pret.statut }}</span>
                                                {% elseif pret.statut == 'En attente' %}
                                                    <span class="badge bg-warning text-dark">{{ pret.statut }}</span>
                                                {% elseif pret.statut == 'Rejeté' %}
                                                    <span class="badge bg-danger">{{ pret.statut }}</span>
                                                {% else %}
                                                    <span class="badge bg-secondary">{{ pret.statut }}</span>
                                                {% endif %}
                                            </td>
                                            <td>
                                                {% if pret.statut == 'En attente' %}
                                                    <a href="{{ path('admin_pret_valider', {'id': pret.id}) }}" class="btn btn-success btn-sm">Valider</a>
                                                    <a href="{{ path('admin_pret_rejeter', {'id': pret.id}) }}" class="btn btn-danger btn-sm">Rejeter</a>
                                                {% endif %}
                                            </td>

                                        </tr>
                                    {% endfor %}
                                        </tbody>
                                        </table>
                                       <div class="navigation">
                                            {{ knp_pagination_render(prets) }}
                                        </div>


                                    {% endif %} 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            
     
{% endblock %}

templates/demande/mesdemandes.html.twig
{% extends 'baseF.html.twig' %}

{% block body %}
    <div class="row mb-4">
        <div class="col-12">
            <h1>Mes Attestations</h1>
            <div class="card">
                <div class="card-body">
                    {% if demandes is empty %}
                        <div class="alert alert-info mt-3">Aucun attestation trouvé.</div>
                    {% else %}
                        <table class="table table-striped table-bordered mt-3">
                            <thead class="bg-primary text-white">
                                <tr>
                                    <th>Type</th>
                                    <th>Statut</th>
                                    <th>Date</th>
                                    <th>Actions</th>
                                    <th>Télecharger</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for demande in demandes %}
                                    <tr>
                                        <td>{{ demande.type }}</td>
                                        <td>
                                            {% if demande.statut == 'Validée' %}
                                                <span class="badge bg-success">{{ demande.statut }}</span>
                                            {% elseif demande.statut == 'En attente' %}
                                                <span class="badge bg-warning text-dark">{{ demande.statut }}</span>
                                            {% elseif demande.statut == 'Rejetée' %}
                                                <span class="badge bg-danger">{{ demande.statut }}</span>
                                            {% else %}
                                                <span class="badge bg-secondary">{{ demande.statut }}</span>
                                            {% endif %}
                                        </td>
                                        <td>{{ demande.dateSoumission|date('d/m/Y') }}</td>
                                        <td>
                                            <a href="{{ path('app_demande_show', { idDem: demande.idDem }) }}" class="btn btn-sm btn-primary">Voir</a>
                                        </td>
                                        <td>
                                            {% if demande.statut == 'Validée' %}
                                                <a href="{{ path('admin_demande_pdf', {'idDem': demande.idDem}) }}" 
                                                  class="btn btn- btn-sm" target="_blank">
                                                    📄 Télécharger PDF
                                                </a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {{ knp_pagination_render(demandes) }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-12">
            <h1>Mes Prêts</h1>
            <div class="card">
                <div class="card-body">
                    {% if prets is empty %}
                        <div class="alert alert-info mt-3">Aucun prêt trouvé.</div>
                    {% else %}
                        <table class="table table-striped table-bordered mt-3">
                            <thead class="bg-primary text-white">
                                <tr>
                                    
                                    <th>Montant</th>
                                    <th>Raison</th>
                                    <th>Date</th>
                                    <th>Statut</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for pret in prets %}
                                    <tr>
                                    
                                        <td>{{ pret.montant }}</td>
                                        <td>{{ pret.raison }}</td>
                                        <td>{{ pret.dateDemande|date('d/m/Y') }}</td>
                                        <td>
                                            {% if pret.statut == 'Validé' %}
                                                <span class="badge bg-success">{{ pret.statut }}</span>
                                            {% elseif pret.statut == 'En attente' %}
                                                <span class="badge bg-warning text-dark">{{ pret.statut }}</span>
                                            {% elseif pret.statut == 'Rejeté' %}
                                                <span class="badge bg-danger">{{ pret.statut }}</span>
                                            {% else %}
                                                <span class="badge bg-secondary">{{ pret.statut }}</span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {{ knp_pagination_render(prets) }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

     <div class="row mb-4">
        <div class="col-12">
            <h1>Mes Avances</h1>
            <div class="card">
                <div class="card-body">
                    {% if avances is empty %}
                        <div class="alert alert-info mt-3">Aucune avnance trouvé.</div>
                    {% else %}
                        <table class="table table-striped table-bordered mt-3">
                            <thead class="bg-primary text-white">
                                <tr>
                                    
                                    <th>Montant</th>
                                    <th>Raison</th>
                                    <th>Date</th>
                                    <th>Statut</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for avance in avances %}
                                    <tr>
                                        
                                        <td>{{ avance.montant }}</td>
                                        <td>{{ avance.raison }}</td>
                                        <td>{{ avance.date_demande|date('d/m/Y') }}</td>
                                        <td>
                                            {% if avance.statut == 'Validée' %}
                                                <span class="badge bg-success">{{ avance.statut }}</span>
                                            {% elseif avance.statut == 'En attente' %}
                                                <span class="badge bg-warning text-dark">{{ avance.statut }}</span>
                                            {% elseif avance.statut == 'Rejeté' %}
                                                <span class="badge bg-danger">{{ avance.statut }}</span>
                                            {% else %}
                                                <span class="badge bg-secondary">{{ avance.statut }}</span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {{ knp_pagination_render(avances) }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/demande/new.html.twig
{% extends 'baseF.html.twig' %}

{% block title %}New Demande{% endblock %}

{% block body %}

    {{ include('demande/_form.html.twig') }}

    <a href="{{ path('app_mes_demandes') }}" class="btn btn-outline-secondary btn-sm">
       <i class="fas fa-arrow-left"></i> Retour 
    </a>
{% endblock %}

templates/demande/show.html.twig
{% extends 'baseF.html.twig' %}

{% block title %}Demande{% endblock %}

{% block body %}
    <h1>Demande</h1>

    <table class="table">
        <tbody>
            
            <tr>
                <th>Type</th>
                <td>{{ demande.type }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ demande.statut }}</td>
            </tr>
            <tr>
                <th>Date_soumission</th>
                <td>{{ demande.dateSoumission ? demande.dateSoumission|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            
        </tbody>
    </table>

   <a href="{{ path('app_mes_demandes') }}" class="btn btn-outline-secondary btn-sm">
      <i class="fas fa-arrow-left"></i> Retour 
   </a>


    

    {{ include('demande/_delete_form.html.twig') }}
{% endblock %}